/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/OuwDOVoSc17
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export function ui() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100 dark:bg-gray-950">
      <div className="mx-auto max-w-md space-y-6">
        <div className="space-y-2 text-center">
          <h1 className="text-3xl font-bold">Welcome to SyllySync</h1>
          <p className="text-gray-500 dark:text-gray-400">Seamlessly sync your syllabus to your Google Calendar.</p>
        </div>
        <div className="space-y-4">
          <Button className="w-full" variant="outline">
            <ChromeIcon className="h-5 w-5 mr-2" />
            Sign in with Google
          </Button>
          <div className="flex items-center">
            <div className="h-px flex-1 bg-gray-300 dark:bg-gray-700" />
            <span className="mx-4 text-gray-500 dark:text-gray-400">or</span>
            <div className="h-px flex-1 bg-gray-300 dark:bg-gray-700" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="syllabus">Upload Syllabus</Label>
            <Input id="syllabus" type="file" />
          </div>
          <Button className="w-full">Sync to Google Calendar</Button>
        </div>
      </div>
    </main>
  )
}

function ChromeIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <circle cx="12" cy="12" r="4" />
      <line x1="21.17" x2="12" y1="8" y2="8" />
      <line x1="3.95" x2="8.54" y1="6.06" y2="14" />
      <line x1="10.88" x2="15.46" y1="21.94" y2="14" />
    </svg>
  )
}
